version: '3.8'
services:
  app:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - .:/usr/src/app:delegated
    environment:
      - NODE_ENV=development
    command: ["npx", "nodemon"]
