version: '3.8'
services:
  app:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: ["npm", "start", "--", "--host", "0.0.0.0", "--port", "8089", "--cache", "./cache"]
